"use client";

import { useState } from "react";
import { Download, ChevronDown, FileText, FileDown } from "lucide-react";
import { formatDataForPDF } from "./SummaryArea.utils";

// 导出下拉组件
export function ExportDropdown({ data, toast }: any) {
  const [isOpen, setIsOpen] = useState(false);

  const exportAsText = () => {
    const blob = new Blob([data], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "ai-analysis.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Exported as TXT file");
    setIsOpen(false);
  };

  const exportAsMarkdown = () => {
    const blob = new Blob([data], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "ai-analysis.md";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Exported as Markdown file");
    setIsOpen(false);
  };

  const exportAsPDF = async () => {
    try {
      // 使用浏览器的打印功能生成PDF
      const printWindow = window.open("", "_blank");
      if (!printWindow) return;

      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>AI Analysis Report</title>
          <style>
            body {
              font-family: var(--font-body-stack), "Cereal", "Airbnb Cereal App", "Circular Std", "Avenir Next", "Inter", system-ui, -apple-system, "Segoe UI", sans-serif;
              line-height: 1.6;
              max-width: 800px;
              margin: 0 auto;
              padding: 40px 20px;
              color: #333;
            }
            h1, h2, h3 { color: #2563eb; margin-top: 2em; }
            h1 { border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5em; }
            pre { background: #f8fafc; padding: 1em; border-radius: 8px; overflow-x: auto; }
            blockquote { border-left: 4px solid #3b82f6; margin: 1em 0; padding-left: 1em; }
            .card { background: #f8fafc; border: 1px solid #e5e7eb; border-radius: 8px; padding: 1em; margin: 1em 0; }
            .question { font-weight: bold; color: #1e40af; }
            .answer { margin-top: 0.5em; }
          </style>
        </head>
        <body>
          <h1>AI Analysis Report</h1>
          <div>${formatDataForPDF(data)}</div>
          <footer style="margin-top: 3em; padding-top: 1em; border-top: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 0.9em;">
            Generated by YTvidHub &bull; ${new Date().toLocaleDateString()}
          </footer>
        </body>
        </html>
      `);

      printWindow.document.close();
      printWindow.focus();

      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 500);

      toast.success("PDF export initiated");
      setIsOpen(false);
    } catch (error) {
      toast.error("PDF export failed");
    }
  };

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 px-3 py-2 text-sm font-medium text-slate-600 hover:text-slate-800 hover:bg-slate-100 rounded-lg transition-all"
      >
        <Download size={16} />
        Export
        <ChevronDown
          size={14}
          className={`transition-transform ${isOpen ? "rotate-180" : ""}`}
        />
      </button>

      {isOpen && (
        <>
          <div
            className="fixed inset-0 z-10"
            onClick={() => setIsOpen(false)}
          />
          <div className="absolute right-0 top-full mt-2 w-48 bg-white border border-slate-200 rounded-lg shadow-lg z-20 py-2">
            <button
              onClick={exportAsText}
              className="w-full flex items-center gap-3 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50 transition-all"
            >
              <FileText size={16} />
              <div className="text-left">
                <div className="font-medium">Text File</div>
                <div className="text-xs text-slate-500">.txt format</div>
              </div>
            </button>

            <button
              onClick={exportAsMarkdown}
              className="w-full flex items-center gap-3 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50 transition-all"
            >
              <FileDown size={16} />
              <div className="text-left">
                <div className="font-medium">Markdown</div>
                <div className="text-xs text-slate-500">.md format</div>
              </div>
            </button>

            <button
              onClick={exportAsPDF}
              className="w-full flex items-center gap-3 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50 transition-all"
            >
              <FileText size={16} />
              <div className="text-left">
                <div className="font-medium">PDF Document</div>
                <div className="text-xs text-slate-500">Print to PDF</div>
              </div>
            </button>
          </div>
        </>
      )}
    </div>
  );
}
